---
- hosts: all
  roles:
    - rxe

- hosts: all
  tasks:
    - name: Install build requirements
      become: true
      package:
        name: 
          - gcc
          - make
          - g++
        state: latest

- hosts: all
  tasks:
    - name: Install dev tools 
      become: true
      package:
        name: 
          - vim
        state: latest
